FROM --platform=linux/amd64  pytorch/pytorch:2.4.0-cuda12.4-cudnn9-devel
RUN apt update \
    && DEBIAN_FRONTEND=noninteractive apt install -y tzdata git\
    && rm -rf /var/lib/apt/lists/*

# 设置默认时区
ENV TZ=Asia/Shanghai
WORKDIR /workspace

COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

COPY ./routers /workspace/routers
COPY ./dependencies /workspace/dependencies
COPY ./utils /workspace/utils
COPY ./aigc_server.py /workspace/

CMD ["uvicorn", "aigc_server:app","--host","0.0.0.0","--port","8006"]