FROM --platform=linux/amd64  registry.cn-shanghai.aliyuncs.com/shnguo/pytorch.pytorch:2.4.0-cuda12.4-cudnn9-devel
RUN apt update \
    && DEBIAN_FRONTEND=noninteractive apt install -y tzdata git\
    && rm -rf /var/lib/apt/lists/*

# 设置默认时区
ENV TZ=Asia/Shanghai
WORKDIR /workspace

# COPY ./mbart-large-50-many-to-one-mmt ./mbart-large-50-many-to-one-mmt
COPY ./vit-large-patch16-224-in21k /workspace/vit-large-patch16-224-in21k
COPY ./ViT-B /workspace/ViT-B
COPY ./CLIP /workspace/CLIP
COPY ./bge-m3 /workspace/bge-m3
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

RUN pip install /workspace/CLIP
COPY ./utils /workspace/utils

COPY ./bge-vit-server.py /workspace/



CMD ["uvicorn", "bge-vit-server:app","--host","0.0.0.0","--port","8005"]